spring:
  lighthouse:
    url: https://api.siterelic.com/lighthouse
    api-key: ${LIGHTHOUSE_API_KEY}
  jms:
    listener:
      concurrency: 5
    pub-sub-domain: true
  datasource:
    url: jdbc:postgresql://localhost:5432/HackScore
    username: postgres
    password: 4560
  jpa:
    show:
      sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.tool.schema: debug

  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-4
          temperature: 1



solace:
  jms:
    host: ${SOLACE_JMS_HOST}
    vpn: ${SOLACE_JMS_VPN}
    username: ${SOLACE_JMS_USERNAME}
    password: ${SOLACE_JMS_PASSWORD}

clerk:
  secret:
    key: ${CLERK_SECRET_KEY}



